name: base
dependencies:
- numpy=1.21.2
- pillow=8.4.0
- pip=21.2.4
- python=3.9.7
- pytorch::pytorch=1.10.0=py3.9_cpu_0
- scipy=1.7.1
- pytorch::torchvision=0.11.1=py39_cpu
- tqdm=4.62.3
- torchvision